language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy3

jobs:
  include:
    - name: flake8
      install: pip install tox
      script: tox -e flake8
      after_script:

cache: pip
install:
  - pip install pytest coverage coveralls
script:
  - coverage run -m pytest
  - coverage report -m --fail-under=100
after_script:
  - coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net##mgedmin"
    on_success: change
    on_failure: always
    template:
      # ping my nick so I get a pushbullet notification on my phone
      - "mgedmin: %{repository_name} (%{branch}) build %{result}: %{build_url}"
